plausible-analytics:
  baseURL: http://plausible-analytics.ujstor.com
  disableRegistration: false
  customIngress:
    enabled: true
    className: "nginx"
    servicePort: 80
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
      - host: plausible-analytics.ujstor.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: plausible-analytics-tls
        hosts:
          - plausible-analytics.ujstor.com
