plausible-analytics:
  baseURL: http://plausible-analytics.ujstor.com
  disableRegistration: false
  ingress:
    enabled: true
    className: "nginx"
    pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/websocket-services: "plausible-analytics"
    hosts:
      - host: plausible-analytics.ujstor.com
    path: /
    tls:
      - secretName: plausible-analytics-tls
        hosts:
          - plausible-analytics.ujstor.com
