plausible:
  plausible-analytics:
    image:
      repository: docker.io/plausible/analytics
      tag: "v2.0.0"

    baseURL: https://plausible-analytics.ujstor.com
    disableRegistration: false

  customIngress:
    enabled: true
    hosts:
      - host: plausible-analytics.ujstor.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: plausible-analytics-tls
        hosts:
          - plausible-analytics.ujstor.com
