plausible-analytics:
  baseURL: https://plausible-analytics.ujstor.com
  disableRegistration: false
  customIngress:
    enabled: true
    hosts:
      - host: plausible-analytics.ujstor.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: plausible-analytics-tls
        hosts:
          - plausible-analytics.ujstor.com
