uptime:
  uptime-kuma:
    ingress:
      enabled: true
      hosts:
        - host: uptime.k3s4.ujstor.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: uptime-kuma-tls
          hosts:
            - uptime.k3s4.ujstor.com
