mailserver:
  dockermailserver:
    deployment:
      env:
        OVERRIDE_HOSTNAME: mail.k3s.ujstor.com
    certificate: mailserver-tls

  certificates:
    organization: Ujstor
    duration: 2160h
    renewBefore: 360h
    issuerRef:
      name: letsencrypt-issuer
      kind: Issuer
