vault-k3s:
  vault:
    server:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        hosts:
          - host: vault.k3s.ujstor.com
            paths:
              - /
        tls:
          - secretName: vault-tls
            hosts:
              - vault.k3s.ujstor.com
