apiVersion: v2
name: todo-django
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.1"

dependencies:
- name: todo-django
  version: 1.0.0
  repository: "https://ujstor.github.io/helm-charts-github-apps"
