apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-cluster-issuer
  namespace: gitops
spec:
  destination:
    namespace: cert-managerc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/system/cluster-issuer
    repoURL: https://github.com/Ujstor/k3s-single-node-iac
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
