apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-ingress-nginx
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/system/ingress-nginx
    repoURL: https://github.com/Ujstor/k3s-single-node-iac
    targetRevision: master
    helm:
      releaseName: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
