apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-argocd
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/hook-dependency: system-argocd
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/system/argocd
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
