apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-vault
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/system/vault
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Replace=true
