apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-prometheus-grafana
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  destination:
    namespace: prometheus-grafana
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/system/prometheus-grafana
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: kube-prometheus-stack
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
