apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-github-readme-stats
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    namespace: github-readme-stats
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/apps/github-readme-stats
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: github-readme-stats
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
