apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-mailserver
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "13"
spec:
  destination:
    namespace: mailserver
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/apps/mailserver
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: mailserver
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
