apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-fastapi
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  destination:
    namespace: fastapi
    server: https://kubernetes.default.svc
  project: ops-cluster-bootstrap
  source:
    path: helm/apps/fastapi
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: fastapi
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
