apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-uptime-kuma
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  destination:
    namespace: uptime-kuma
    server: https://kubernetes.default.svc
  project: cluster-bootstrap
  source:
    path: helm/apps/uptime-kuma
    repoURL: https://github.com/Ujstor/k3s-single-node-iac.git
    targetRevision: master
    helm:
      version: v3
      releaseName: uptime-kuma
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
