gitea-k3s:
  gitea:
    ingress:
      enabled: true
      hosts:
        - host: gitea.k3s.ujstor.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: gitea-tls
          hosts:
            - gitea.k3s.ujstor.com

    persistence:
      size: 20Gi
    redis-cluster:
      enabled: false
    postgresql-ha:
      enabled: false
    redis:
      enabled: true
    postgresql:
      enabled: true
      primary:
        persistence:
          size: 2Gi
